"""Remove old category string column from Task

Revision ID: 0bee5bfdc436
Revises: 91e4599230d0
Create Date: 2026-01-29 22:23:12.083802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bee5bfdc436'
down_revision = '91e4599230d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_task_category_id', 'category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_task_category_id', type_='foreignkey')

    # ### end Alembic commands ###
