"""Add Google Calendar integration fields

Revision ID: 7429496cbcc7
Revises: 46b61ae1069a
Create Date: 2026-01-06 12:28:10.324909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7429496cbcc7'
down_revision = '46b61ae1069a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('synced_to_calendar', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('calendar_sync_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calendar_sync_enabled')
        batch_op.drop_column('google_calendar_id')
        batch_op.drop_column('google_token')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('synced_to_calendar')
        batch_op.drop_column('google_event_id')

    # ### end Alembic commands ###
